// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LPS.Util {
    
    
    public partial class UtilMainWindow {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Entry entry1;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView outputView;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LPS.Util.UtilMainWindow
            this.Name = "LPS.Util.UtilMainWindow";
            this.Title = Mono.Unix.Catalog.GetString("UtilMainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child LPS.Util.UtilMainWindow.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.entry1 = new Gtk.Entry();
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.entry1.InvisibleChar = '●';
            this.vbox2.Add(this.entry1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.entry1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.outputView = new Gtk.TextView();
            this.outputView.CanFocus = true;
            this.outputView.Name = "outputView";
            this.outputView.Editable = false;
            this.GtkScrolledWindow.Add(this.outputView);
            this.vbox2.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
            w3.Position = 1;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.entry1.Activated += new System.EventHandler(this.OnEntry1Activated);
        }
    }
}
